# Generated by Django 4.2.13 on 2024-06-21 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='entry',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preview'), (1, 'Posted')], default=0),
        ),
    ]
