# Generated by Django 4.2.13 on 2024-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
